# Generated by Django 4.1.2 on 2022-11-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('PCS', models.CharField(max_length=250, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
