# Generated by Django 4.1.2 on 2022-12-12 15:48

import DatabaseAccounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('PCS', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to=DatabaseAccounts.models.profile_images)),
                ('about', models.TextField(blank=True, max_length=1000, verbose_name='about')),
                ('userP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
