# Generated by Django 4.1.2 on 2022-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAccounts', '0006_alter_profile_pcs_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
