# Generated by Django 4.1.2 on 2022-12-23 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAccounts', '0008_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PCS',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{5}$')]),
        ),
    ]
