# Generated by Django 4.1.2 on 2022-10-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='profile',
        ),
    ]
