# Generated by Django 4.1.2 on 2022-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0002_author_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
