# Generated by Django 4.1.2 on 2022-10-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0002_remove_quiz_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='kind',
            new_name='genre',
        ),
    ]
