# Generated by Django 4.1.2 on 2022-12-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0002_remove_quiz_question_delete2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
    ]
