# Generated by Django 4.1.2 on 2022-12-18 21:19

import DatabaseApps.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0002_review_created_date_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='author',
            name='deathdate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='death date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to=DatabaseApps.models.poster_author_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(null=True, upload_to=DatabaseApps.models.poster_book_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0, help_text='Enter between 1 - 5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='nation',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='state',
            field=models.CharField(blank=True, max_length=250, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(blank=True, default=0, help_text='Enter between 1 - 5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
