# Generated by Django 4.1.2 on 2022-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0003_review_ip_review_text_alter_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
