# Generated by Django 4.1.2 on 2022-11-05 18:14

import DatabaseApps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=DatabaseApps.models.poster_author_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=DatabaseApps.models.poster_book_path),
        ),
    ]
