# Generated by Django 4.1.2 on 2022-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0003_rename_kind_genre_rename_kind_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='quiz',
            field=models.ManyToManyField(null=True, to='DatabaseApps.quiz'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, to='DatabaseApps.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, to='DatabaseApps.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quiz',
            field=models.ManyToManyField(null=True, to='DatabaseApps.quiz'),
        ),
    ]
