# Generated by Django 4.1.2 on 2023-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0004_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='century',
            field=models.ManyToManyField(to='DatabaseApps.century'),
        ),
    ]
