# Generated by Django 4.1.2 on 2022-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0004_alter_author_photo_alter_book_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorHasBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to='DatabaseApps.author')),
                ('book', models.ManyToManyField(to='DatabaseApps.book')),
            ],
        ),
    ]
