# Generated by Django 4.1.2 on 2022-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0004_alter_author_quiz_alter_book_author_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='quiz',
        ),
    ]
