# Generated by Django 4.1.2 on 2022-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0005_remove_author_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='DatabaseApps.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='DatabaseApps.genre'),
        ),
    ]
