# Generated by Django 4.1.2 on 2023-01-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApps', '0006_alter_century_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='city',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
    ]
